services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.build
    image: vance-web:latest
    container_name: vance-web
    expose:
      - 5173
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web/:/app/apps/web
    networks:
      - app_network

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile.build
    image: vance-server:latest
    container_name: vance-server
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./apps/server/:/app/apps/server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
